id: P005433
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4307
  title: ཚད་མ་རིགས་ཐིགས་ཀྱི་འགྲེལ་པ་ཟུར་བཀོལ
  author: ''
  volumes:
    3758c5b1c321427a835040400b7d8b1f:
      image_group_id: I1PD100521
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
