id: I44472BCE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:09:20+00:00'
last_modified: '2022-06-08T03:03:24.515392+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4307
  title: ཚད་མ་རིགས་ཐིགས་ཀྱི་འགྲེལ་པ་ཟུར་བཀོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B8E6:
      image_group_id: I1PD100521
      title: ''
      total_pages: 112
      order: 1
      base_file: B8E6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
